import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localfont from "next/font/local";
import  SessionProvider  from "@/components/SessionProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LELEKART",
  description: "Generated by create next app",
};

const urbanist = localfont({
  src: [
    {
      path: "../fonts/Urbanist/Urbanist.ttf",
    },
  ],
  variable: "--font-urbanist",
});

const acumin = localfont({
  src: [
    {
      path: "../fonts/Acumin/Acumin-RPro.otf",
    },
  ],
  variable: "--font-acumin",
});

const anton = localfont({
  src: [
    {
      path: "../fonts/Anton/Anton-Regular.ttf",
    },
  ],
  variable: "--font-anton",
});

const arimo = localfont({
  src: [
    {
      path: "../fonts/Arimo/Arimo.ttf",
    },
  ],
  variable: "--font-arimo",
});

const bebas = localfont({
  src: [
    {
      path: "../fonts/Bebas_Neue/BebasNeue.ttf",
    },
  ],
  variable: "--font-bebas",
});

const bungee = localfont({
  src: [
    {
      path: "../fonts/Bungee/Bungee.ttf",
    },
  ],
  variable: "--font-bungee",
});

const lilita = localfont({
  src: [
    {
      path: "../fonts/Lilita_One/Lilita.ttf",
    },
  ],
  variable: "--font-lilita",
});

const outfit = localfont({
  src: [
    {
      path: "../fonts/Outfit/Outfit.ttf",
    },
  ],
  variable: "--font-outfit",
});

const oxygen = localfont({
  src: [
    {
      path: "../fonts/Oxygen/Oxygen.ttf",
    },
  ],
  variable: "--font-oxygen",
});

const pacifico = localfont({
  src: [
    {
      path: "../fonts/Pacifico/Pacifico.ttf",
    },
  ],
  variable: "--font-pacifico",
});

const reddit = localfont({
  src: [
    {
      path: "../fonts/Reddit_Sans/Reddit.ttf",
    },
  ],
  variable: "--font-reddit",
});







export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className} ${urbanist.variable} ${acumin.variable} ${bebas.variable} ${arimo.variable} ${anton.variable} ${bungee.variable} ${lilita.variable}  ${outfit.variable} ${oxygen.variable} ${pacifico.variable} ${reddit.variable} `}>
        <SessionProvider session={session}>
        {children}
        </SessionProvider>
        </body>
    </html>
  );
}
